name: flutter_widgets
description: A sample application to demonstrate Flutter widgets.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  webview_flutter: ^0.3.10+3

  shared_preferences: ^0.5.6


  moor: ^3.3.1

  #Phasing out moor_ffi: https://github.com/simolus3/moor/issues/691
  # Database for mobile and Desktop
  #moor_ffi: ^0.3.0

  sqlite3_flutter_libs: ^0.2.0

  # Helper to find the database path on mobile
  path_provider: ^1.5.1
  path: ^1.6.4

  provider: ^3.1.0 #ChangeNotifier, Consumer, Providers

  #firebase auth for Google SignIn
  google_sign_in: ^4.3.0 #google signin
#
#  firebase_core: ^0.4.0+9
#  firebase: any
#  firebase_auth: ^0.14.0+4 #user auth
  cloud_firestore: ^0.12.9+1 #saving user profiles

  #firebase: ^5.0.4
  fb_auth: ^0.0.2+1
  firebase_storage: ^3.0.8
  firebase_analytics: ^5.0.6

  universal_html: ^1.1.0
  url_launcher: ^5.1.2
  font_awesome_flutter: ^8.5.0

  #dismissible widgets
  flutter_slidable: ^0.5.4

  #Flutter Text-to-speech dep
  flutter_tts: ^0.7.0

  #http to download PDF
  http: ^0.12.0+4
  #Open PDF in a viewer
  flutter_full_pdf_viewer: ^1.0.6

  #placeholder transparent images
  transparent_image: ^1.0.0

  #Share with other apps
  share_extend: "^1.1.1"

  syntax_highlighter: ^0.1.0
  animated_floatactionbuttons: ^0.1.0

#  flutter_colorpicker: ^0.2.6

#  screenshot: ^0.1.1
#  image_gallery_saver: ^1.2.2

  #Local database
  sqflite: ^1.3.0

  #Picking image from gallery
  image_picker: ^0.6.7+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.2
  moor_generator: ^3.3.1

#  built_value_generator: ^6.5.0

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - assets/flutter-to-fly-creds.json
    - assets/images/sea-rocks.jpg
    - assets/images/sea2.jpg
    - assets/images/sea3.jpg
    - assets/images/griffith_observatory.jpg
    - assets/images/menu.png
    - assets/images/tomato.jpg
    - assets/images/flutter_slides.jpg
    - lib/pdf/
    - lib/images/
    - lib/lists/
    - lib/login/
    - lib/menus/
    - lib/quizzie/
    - lib/sliders/
    - lib/swtch/
    - lib/themes/db/
    - lib/themes/sharedPrefs/
    - lib/tts/


  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
